In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from matplotlib import rcParams
rcParams['figure.figsize'] = 15, 5
sns.set_style('darkgrid')

In [3]:
patient_df = pd.read_csv('dataset.csv')
patient_df.head()

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,Unnamed: 83,hospital_death
0,66154,25312,118,68.0,22.73,0,Caucasian,M,180.3,Floor,...,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular,NaN,0
1,114252,59342,81,77.0,27.42,0,Caucasian,F,160.0,Floor,...,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory,NaN,0
2,119783,50777,118,25.0,31.95,0,Caucasian,F,172.7,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,NaN,0
3,79267,46918,118,81.0,22.64,1,Caucasian,F,165.1,Operating Room / Recovery,...,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,NaN,0
4,92056,34377,33,19.0,NaN,0,Caucasian,M,188.0,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma,NaN,0

In [4]:
patient_df.describe()

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,height,icu_id,pre_icu_los_days,weight,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,Unnamed: 83,hospital_death
count,91713.000000,91713.000000,91713.000000,87485.000000,88284.000000,91713.000000,90379.000000,91713.000000,91713.000000,88993.000000,...,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,0.0,91713.000000
mean,65606.079280,65537.131464,105.669262,62.309516,29.185818,0.183736,169.641588,508.357692,0.835766,84.028340,...,0.000857,0.015693,0.225192,0.012989,0.026165,0.007066,0.004132,0.020638,NaN,0.086302
std,37795.088538,37811.252183,62.854406,16.775119,8.275142,0.387271,10.795378,228.989661,2.487756,25.011497,...,0.029265,0.124284,0.417711,0.113229,0.159628,0.083763,0.064148,0.142169,NaN,0.280811
min,1.000000,1.000000,2.000000,16.000000,14.844926,0.000000,137.200000,82.000000,-24.947222,38.600000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
25%,32852.000000,32830.000000,47.000000,52.000000,23.641975,0.000000,162.500000,369.000000,0.035417,66.800000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
50%,65665.000000,65413.000000,109.000000,65.000000,27.654655,0.000000,170.100000,504.000000,0.138889,80.300000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
75%,98342.000000,98298.000000,161.000000,75.000000,32.930206,0.000000,177.800000,679.000000,0.409028,97.100000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
max,131051.000000,131051.000000,204.000000,89.000000,67.814990,1.000000,195.590000,927.000000,159.090972,186.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,1.000000

In [5]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91713 entries, 0 to 91712
Data columns (total 85 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   encounter_id                   91713 non-null  int64
 1   patient_id                     91713 non-null  int64
 2   hospital_id                    91713 non-null  int64
 3   age                            87485 non-null  float64
 4   bmi                            88284 non-null  float64
 5   elective_surgery               91713 non-null  int64
 6   ethnicity                      90318 non-null  object
 7   gender                         91688 non-null  object
 8   height                         90379 non-null  float64
 9   icu_admit_source               91601 non-null  object
 10  icu_id                         91713 non-null  int64
 11  icu_stay_type                  91713 non-null  object
 12  icu_type                       91713 non-null  object
 13  pre_icu_los_days               91713 non-null  float64
 14  weight                         88993 non-null  float64
 15  apache_2_diagnosis             90051 non-null  float64
 16  apache_3j_diagnosis            90612 non-null  float64
 17  apache_post_operative          91713 non-null  int64
 18  arf_apache                     90998 non-null  float64
 19  gcs_eyes_apache                89812 non-null  float64
 20  gcs_motor_apache               89812 non-null  float64
 21  gcs_unable_apache              90676 non-null  float64
 22  gcs_verbal_apache              89812 non-null  float64
 23  heart_rate_apache              90835 non-null  float64
 24  intubated_apache               90998 non-null  float64
 25  map_apache                     90719 non-null  float64
 26  resprate_apache                90479 non-null  float64
 27  temp_apache                    87605 non-null  float64
 28  ventilated_apache              90998 non-null  float64
 29  d1_diasbp_max                  91548 non-null  float64
 30  d1_diasbp_min                  91548 non-null  float64
 31  d1_diasbp_noninvasive_max      90673 non-null  float64
 32  d1_diasbp_noninvasive_min      90673 non-null  float64
 33  d1_heartrate_max               91568 non-null  float64
 34  d1_heartrate_min               91568 non-null  float64
 35  d1_mbp_max                     91493 non-null  float64
 36  d1_mbp_min                     91493 non-null  float64
 37  d1_mbp_noninvasive_max         90234 non-null  float64
 38  d1_mbp_noninvasive_min         90234 non-null  float64
 39  d1_resprate_max                91328 non-null  float64
 40  d1_resprate_min                91328 non-null  float64
 41  d1_spo2_max                    91380 non-null  float64
 42  d1_spo2_min                    91380 non-null  float64
 43  d1_sysbp_max                   91554 non-null  float64
 44  d1_sysbp_min                   91554 non-null  float64
 45  d1_sysbp_noninvasive_max       90686 non-null  float64
 46  d1_sysbp_noninvasive_min       90686 non-null  float64
 47  d1_temp_max                    89389 non-null  float64
 48  d1_temp_min                    89389 non-null  float64
 49  h1_diasbp_max                  88094 non-null  float64
 50  h1_diasbp_min                  88094 non-null  float64
 51  h1_diasbp_noninvasive_max      84363 non-null  float64
 52  h1_diasbp_noninvasive_min      84363 non-null  float64
 53  h1_heartrate_max               88923 non-null  float64
 54  h1_heartrate_min               88923 non-null  float64
 55  h1_mbp_max                     87074 non-null  float64
 56  h1_mbp_min                     87074 non-null  float64
 57  h1_mbp_noninvasive_max         82629 non-null  float64
 58  h1_mbp_noninvasive_min         82629 non-null  float64
 59  h1_resprate_max                87356 non-null  float64
 60  h1_resprate_min                87356 non-null  float64
 61  h1_spo2_max                    87528 non-null  float64
 62  h1_spo2_min                    87528 non-null  float64
 63  h1_sysbp_max                   88102 non-null  float64
 64  h1_sysbp_min                   88102 non-null  float64
 65  h1_sysbp_noninvasive_max       84372 non-null  float64
 66  h1_sysbp_noninvasive_min       84372 non-null  float64
 67  d1_glucose_max                 85906 non-null  float64
 68  d1_glucose_min                 85906 non-null  float64
 69  d1_potassium_max               82128 non-null  float64
 70  d1_potassium_min               82128 non-null  float64
 71  apache_4a_hospital_death_prob  83766 non-null  float64
 72  apache_4a_icu_death_prob       83766 non-null  float64
 73  aids                           90998 non-null  float64
 74  cirrhosis                      90998 non-null  float64
 75  diabetes_mellitus              90998 non-null  float64
 76  hepatic_failure                90998 non-null  float64
 77  immunosuppression              90998 non-null  float64
 78  leukemia                       90998 non-null  float64
 79  lymphoma                       90998 non-null  float64
 80  solid_tumor_with_metastasis    90998 non-null  float64
 81  apache_3j_bodysystem           90051 non-null  object
 82  apache_2_bodysystem            90051 non-null  object
 83  Unnamed: 83                    0 non-null      float64
 84  hospital_death                 91713 non-null  int64
dtypes: float64(71), int64(7), object(7)
memory usage: 59.5+ MB

In [6]:
patient_df.isnull().sum()

encounter_id                       0
patient_id                         0
hospital_id                        0
age                             4228
bmi                             3429
                               ...
solid_tumor_with_metastasis      715
apache_3j_bodysystem            1662
apache_2_bodysystem             1662
Unnamed: 83                    91713
hospital_death                     0
Length: 85, dtype: int64

In [7]:
patient_df.nunique()

encounter_id                   91713
patient_id                     91713
hospital_id                      147
age                               74
bmi                            34888
                               ...
solid_tumor_with_metastasis        2
apache_3j_bodysystem              11
apache_2_bodysystem               10
Unnamed: 83                        0
hospital_death                     2
Length: 85, dtype: int64

In [8]:
patient_df.drop(labels=['apache_3j_bodysystem','apache_2_bodysystem'], axis=1, inplace=True)
patient_df = pd.get_dummies(data=patient_df, columns=['ethnicity', 'gender','icu_admit_source','icu_stay_type','icu_type'], drop_first=True)

In [9]:
mean_age = int(patient_df['age'].mean())
patient_df['age'] = patient_df['age'].apply(lambda age : mean_age if pd.isnull(age) else age)

mean_bmi = int(patient_df['bmi'].mean())
patient_df['bmi'] = patient_df['bmi'].apply(lambda bmi : mean_bmi if pd.isnull(bmi) else bmi)

mean_height = int(patient_df['height'].mean())
patient_df['height'] = patient_df['height'].apply(lambda height : mean_height if pd.isnull(height) else height)

mean_weight = int(patient_df['weight'].mean())
patient_df['weight'] = patient_df['weight'].apply(lambda weight : mean_weight if pd.isnull(weight) else weight)

mean_apache_2_diagnosis = int(patient_df['apache_2_diagnosis'].mean())
patient_df['apache_2_diagnosis'] = patient_df['apache_2_diagnosis'].apply(lambda apache_2_diagnosis : mean_apache_2_diagnosis if pd.isnull(apache_2_diagnosis) else apache_2_diagnosis)

mean_apache_3j_diagnosis = int(patient_df['apache_3j_diagnosis'].mean())
patient_df['apache_3j_diagnosis'] = patient_df['apache_3j_diagnosis'].apply(lambda apache_3j_diagnosis : mean_apache_3j_diagnosis if pd.isnull(apache_3j_diagnosis) else apache_3j_diagnosis)

mean_arf_apache = int(patient_df['arf_apache'].mean())
patient_df['arf_apache'] = patient_df['arf_apache'].apply(lambda arf_apache : mean_arf_apache if pd.isnull(arf_apache) else arf_apache)

mean_gcs_eyes_apache = int(patient_df['gcs_eyes_apache'].mean())
patient_df['gcs_eyes_apache'] = patient_df['gcs_eyes_apache'].apply(lambda gcs_eyes_apache : mean_gcs_eyes_apache if pd.isnull(gcs_eyes_apache) else gcs_eyes_apache)

mean_gcs_motor_apache = int(patient_df['gcs_motor_apache'].mean())
patient_df['gcs_motor_apache'] = patient_df['gcs_motor_apache'].apply(lambda gcs_motor_apache : mean_gcs_motor_apache if pd.isnull(gcs_motor_apache) else gcs_motor_apache)

mean_gcs_unable_apache = int(patient_df['gcs_unable_apache'].mean())
patient_df['gcs_unable_apache'] = patient_df['gcs_unable_apache'].apply(lambda gcs_unable_apache : mean_gcs_unable_apache if pd.isnull(gcs_unable_apache) else gcs_unable_apache)

mean_gcs_verbal_apache = int(patient_df['gcs_verbal_apache'].mean())
patient_df['gcs_verbal_apache'] = patient_df['gcs_verbal_apache'].apply(lambda gcs_verbal_apache : mean_gcs_verbal_apache if pd.isnull(gcs_verbal_apache) else gcs_verbal_apache)

mean_heart_rate_apache = int(patient_df['heart_rate_apache'].mean())
patient_df['heart_rate_apache'] = patient_df['heart_rate_apache'].apply(lambda heart_rate_apache : mean_heart_rate_apache if pd.isnull(heart_rate_apache) else heart_rate_apache)

mean_intubated_apache = int(patient_df['intubated_apache'].mean())
patient_df['intubated_apache'] = patient_df['intubated_apache'].apply(lambda intubated_apache : mean_intubated_apache if pd.isnull(intubated_apache) else intubated_apache)

mean_map_apache = int(patient_df['map_apache'].mean())
patient_df['map_apache'] = patient_df['map_apache'].apply(lambda map_apache : mean_map_apache if pd.isnull(map_apache) else map_apache)

mean_resprate_apache = int(patient_df['resprate_apache'].mean())
patient_df['resprate_apache'] = patient_df['resprate_apache'].apply(lambda resprate_apache : mean_resprate_apache if pd.isnull(resprate_apache) else resprate_apache)

mean_temp_apache = int(patient_df['temp_apache'].mean())
patient_df['temp_apache'] = patient_df['temp_apache'].apply(lambda temp_apache : mean_temp_apache if pd.isnull(temp_apache) else temp_apache)

mean_ventilated_apache = int(patient_df['ventilated_apache'].mean())
patient_df['ventilated_apache'] = patient_df['ventilated_apache'].apply(lambda ventilated_apache : mean_ventilated_apache if pd.isnull(ventilated_apache) else ventilated_apache)

mean_d1_diasbp_max = int(patient_df['d1_diasbp_max'].mean())
patient_df['d1_diasbp_max'] = patient_df['d1_diasbp_max'].apply(lambda d1_diasbp_max : mean_d1_diasbp_max if pd.isnull(d1_diasbp_max) else d1_diasbp_max)

mean_d1_diasbp_min = int(patient_df['d1_diasbp_min'].mean())
patient_df['d1_diasbp_min'] = patient_df['d1_diasbp_min'].apply(lambda d1_diasbp_min : mean_d1_diasbp_min if pd.isnull(d1_diasbp_min) else d1_diasbp_min)

mean_d1_diasbp_noninvasive_max = int(patient_df['d1_diasbp_noninvasive_max'].mean())
patient_df['d1_diasbp_noninvasive_max'] = patient_df['d1_diasbp_noninvasive_max'].apply(lambda d1_diasbp_noninvasive_max : mean_d1_diasbp_noninvasive_max if pd.isnull(d1_diasbp_noninvasive_max) else d1_diasbp_noninvasive_max)

mean_d1_diasbp_noninvasive_min = int(patient_df['d1_diasbp_noninvasive_min'].mean())
patient_df['d1_diasbp_noninvasive_min'] = patient_df['d1_diasbp_noninvasive_min'].apply(lambda d1_diasbp_noninvasive_min : mean_d1_diasbp_noninvasive_min if pd.isnull(d1_diasbp_noninvasive_min) else d1_diasbp_noninvasive_min)

mean_d1_heartrate_max = int(patient_df['d1_heartrate_max'].mean())
patient_df['d1_heartrate_max'] = patient_df['d1_heartrate_max'].apply(lambda d1_heartrate_max : mean_d1_heartrate_max if pd.isnull(d1_heartrate_max) else d1_heartrate_max)

mean_d1_heartrate_min = int(patient_df['d1_heartrate_min'].mean())
patient_df['d1_heartrate_min'] = patient_df['d1_heartrate_min'].apply(lambda d1_heartrate_min : mean_d1_heartrate_min if pd.isnull(d1_heartrate_min) else d1_heartrate_min)

mean_d1_mbp_max = int(patient_df['d1_mbp_max'].mean())
patient_df['d1_mbp_max'] = patient_df['d1_mbp_max'].apply(lambda d1_mbp_max : mean_d1_mbp_max if pd.isnull(d1_mbp_max) else d1_mbp_max)

mean_d1_mbp_min = int(patient_df['d1_mbp_min'].mean())
patient_df['d1_mbp_min'] = patient_df['d1_mbp_min'].apply(lambda d1_mbp_min : mean_d1_mbp_min if pd.isnull(d1_mbp_min) else d1_mbp_min)

mean_d1_mbp_noninvasive_max = int(patient_df['d1_mbp_noninvasive_max'].mean())
patient_df['d1_mbp_noninvasive_max'] = patient_df['d1_mbp_noninvasive_max'].apply(lambda d1_mbp_noninvasive_max : mean_d1_mbp_noninvasive_max if pd.isnull(d1_mbp_noninvasive_max) else d1_mbp_noninvasive_max)

mean_d1_mbp_noninvasive_min = int(patient_df['d1_mbp_noninvasive_min'].mean())
patient_df['d1_mbp_noninvasive_min'] = patient_df['d1_mbp_noninvasive_min'].apply(lambda d1_mbp_noninvasive_min : mean_d1_mbp_noninvasive_min if pd.isnull(d1_mbp_noninvasive_min) else d1_mbp_noninvasive_min)

mean_d1_resprate_max = int(patient_df['d1_resprate_max'].mean())
patient_df['d1_resprate_max'] = patient_df['d1_resprate_max'].apply(lambda d1_resprate_max : mean_d1_resprate_max if pd.isnull(d1_resprate_max) else d1_resprate_max)

mean_d1_resprate_min = int(patient_df['d1_resprate_min'].mean())
patient_df['d1_resprate_min'] = patient_df['d1_resprate_min'].apply(lambda d1_resprate_min : mean_d1_resprate_min if pd.isnull(d1_resprate_min) else d1_resprate_min)

mean_d1_spo2_max = int(patient_df['d1_spo2_max'].mean())
patient_df['d1_spo2_max'] = patient_df['d1_spo2_max'].apply(lambda d1_spo2_max : mean_d1_spo2_max if pd.isnull(d1_spo2_max) else d1_spo2_max)

mean_d1_spo2_min = int(patient_df['d1_spo2_min'].mean())
patient_df['d1_spo2_min'] = patient_df['d1_spo2_min'].apply(lambda d1_spo2_min : mean_d1_spo2_min if pd.isnull(d1_spo2_min) else d1_spo2_min)

mean_d1_sysbp_noninvasive_max = int(patient_df['d1_sysbp_noninvasive_max'].mean())
patient_df['d1_sysbp_noninvasive_max'] = patient_df['d1_sysbp_noninvasive_max'].apply(lambda d1_sysbp_noninvasive_max : mean_d1_sysbp_noninvasive_max if pd.isnull(d1_sysbp_noninvasive_max) else d1_sysbp_noninvasive_max)

mean_d1_sysbp_noninvasive_min = int(patient_df['d1_sysbp_noninvasive_min'].mean())
patient_df['d1_sysbp_noninvasive_min'] = patient_df['d1_sysbp_noninvasive_min'].apply(lambda d1_sysbp_noninvasive_min : mean_d1_sysbp_noninvasive_min if pd.isnull(d1_sysbp_noninvasive_min) else d1_sysbp_noninvasive_min)

mean_d1_glucose_max = int(patient_df['d1_glucose_max'].mean())
patient_df['d1_glucose_max'] = patient_df['d1_glucose_max'].apply(lambda d1_glucose_max : mean_d1_glucose_max if pd.isnull(d1_glucose_max) else d1_glucose_max)

mean_d1_glucose_min = int(patient_df['d1_glucose_min'].mean())
patient_df['d1_glucose_min'] = patient_df['d1_glucose_min'].apply(lambda d1_glucose_min : mean_d1_glucose_min if pd.isnull(d1_glucose_min) else d1_glucose_min)

mean_d1_potassium_max = int(patient_df['d1_potassium_max'].mean())
patient_df['d1_potassium_max'] = patient_df['d1_potassium_max'].apply(lambda d1_potassium_max : mean_d1_potassium_max if pd.isnull(d1_potassium_max) else d1_potassium_max)

mean_d1_potassium_min = int(patient_df['d1_potassium_min'].mean())
patient_df['d1_potassium_min'] = patient_df['d1_potassium_min'].apply(lambda d1_potassium_min : mean_d1_potassium_min if pd.isnull(d1_potassium_min) else d1_potassium_min)

mean_apache_4a_hospital_death_prob = int(patient_df['apache_4a_hospital_death_prob'].mean())
patient_df['apache_4a_hospital_death_prob'] = patient_df['apache_4a_hospital_death_prob'].apply(lambda apache_4a_hospital_death_prob : mean_apache_4a_hospital_death_prob if pd.isnull(apache_4a_hospital_death_prob) else apache_4a_hospital_death_prob)

mean_apache_4a_icu_death_prob = int(patient_df['apache_4a_icu_death_prob'].mean())
patient_df['apache_4a_icu_death_prob'] = patient_df['apache_4a_icu_death_prob'].apply(lambda apache_4a_icu_death_prob : mean_apache_4a_icu_death_prob if pd.isnull(apache_4a_icu_death_prob) else apache_4a_icu_death_prob)

mean_aids = int(patient_df['aids'].mean())
patient_df['aids'] = patient_df['aids'].apply(lambda aids : mean_aids if pd.isnull(aids) else aids)

mean_cirrhosis = int(patient_df['cirrhosis'].mean())
patient_df['cirrhosis'] = patient_df['cirrhosis'].apply(lambda cirrhosis : mean_cirrhosis if pd.isnull(cirrhosis) else cirrhosis)

mean_diabetes_mellitus = int(patient_df['diabetes_mellitus'].mean())
patient_df['diabetes_mellitus'] = patient_df['diabetes_mellitus'].apply(lambda diabetes_mellitus : mean_diabetes_mellitus if pd.isnull(diabetes_mellitus) else diabetes_mellitus)

mean_hepatic_failure = int(patient_df['hepatic_failure'].mean())
patient_df['hepatic_failure'] = patient_df['hepatic_failure'].apply(lambda hepatic_failure : mean_hepatic_failure if pd.isnull(hepatic_failure) else hepatic_failure)

mean_immunosuppression = int(patient_df['immunosuppression'].mean())
patient_df['immunosuppression'] = patient_df['immunosuppression'].apply(lambda immunosuppression : mean_immunosuppression if pd.isnull(immunosuppression) else immunosuppression)

mean_leukemia = int(patient_df['leukemia'].mean())
patient_df['leukemia'] = patient_df['leukemia'].apply(lambda leukemia : mean_leukemia if pd.isnull(leukemia) else leukemia)

mean_lymphoma = int(patient_df['lymphoma'].mean())
patient_df['lymphoma'] = patient_df['lymphoma'].apply(lambda lymphoma : mean_lymphoma if pd.isnull(lymphoma) else lymphoma)

mean_solid_tumor_with_metastasis = int(patient_df['solid_tumor_with_metastasis'].mean())
patient_df['solid_tumor_with_metastasis'] = patient_df['solid_tumor_with_metastasis'].apply(lambda solid_tumor_with_metastasis : mean_solid_tumor_with_metastasis if pd.isnull(solid_tumor_with_metastasis) else solid_tumor_with_metastasis)

patient_df.drop(labels=['Unnamed: 83'], axis=1, inplace=True)

mean_d1_sysbp_max = int(patient_df['d1_sysbp_max'].mean())
patient_df['d1_sysbp_max'] = patient_df['d1_sysbp_max'].apply(lambda d1_sysbp_max : mean_d1_sysbp_max if pd.isnull(d1_sysbp_max) else d1_sysbp_max)

mean_d1_sysbp_min = int(patient_df['d1_sysbp_min'].mean())
patient_df['d1_sysbp_min'] = patient_df['d1_sysbp_min'].apply(lambda d1_sysbp_min : mean_d1_sysbp_min if pd.isnull(d1_sysbp_min) else d1_sysbp_min)

mean_d1_temp_max = int(patient_df['d1_temp_max'].mean())
patient_df['d1_temp_max'] = patient_df['d1_temp_max'].apply(lambda d1_temp_max : mean_d1_temp_max if pd.isnull(d1_temp_max) else d1_temp_max)

mean_d1_temp_min = int(patient_df['d1_temp_min'].mean())
patient_df['d1_temp_min'] = patient_df['d1_temp_min'].apply(lambda d1_temp_min : mean_d1_temp_min if pd.isnull(d1_temp_min) else d1_temp_min)

mean_h1_diasbp_max = int(patient_df['h1_diasbp_max'].mean())
patient_df['h1_diasbp_max'] = patient_df['h1_diasbp_max'].apply(lambda h1_diasbp_max : mean_h1_diasbp_max if pd.isnull(h1_diasbp_max) else h1_diasbp_max)

mean_h1_diasbp_min = int(patient_df['h1_diasbp_min'].mean())
patient_df['h1_diasbp_min'] = patient_df['h1_diasbp_min'].apply(lambda h1_diasbp_min : mean_h1_diasbp_min if pd.isnull(h1_diasbp_min) else h1_diasbp_min)

mean_h1_diasbp_noninvasive_max = int(patient_df['h1_diasbp_noninvasive_max'].mean())
patient_df['h1_diasbp_noninvasive_max'] = patient_df['h1_diasbp_noninvasive_max'].apply(lambda h1_diasbp_noninvasive_max : mean_h1_diasbp_noninvasive_max if pd.isnull(h1_diasbp_noninvasive_max) else h1_diasbp_noninvasive_max)

mean_h1_diasbp_noninvasive_min = int(patient_df['h1_diasbp_noninvasive_min'].mean())
patient_df['h1_diasbp_noninvasive_min'] = patient_df['h1_diasbp_noninvasive_min'].apply(lambda h1_diasbp_noninvasive_min : mean_h1_diasbp_noninvasive_min if pd.isnull(h1_diasbp_noninvasive_min) else h1_diasbp_noninvasive_min)

mean_h1_heartrate_max = int(patient_df['h1_heartrate_max'].mean())
patient_df['h1_heartrate_max'] = patient_df['h1_heartrate_max'].apply(lambda h1_heartrate_max : mean_h1_heartrate_max if pd.isnull(h1_heartrate_max) else h1_heartrate_max)

mean_h1_heartrate_min = int(patient_df['h1_heartrate_min'].mean())
patient_df['h1_heartrate_min'] = patient_df['h1_heartrate_min'].apply(lambda h1_heartrate_min : mean_h1_heartrate_min if pd.isnull(h1_heartrate_min) else h1_heartrate_min)

mean_h1_mbp_max = int(patient_df['h1_mbp_max'].mean())
patient_df['h1_mbp_max'] = patient_df['h1_mbp_max'].apply(lambda h1_mbp_max : mean_h1_mbp_max if pd.isnull(h1_mbp_max) else h1_mbp_max)

mean_h1_mbp_min = int(patient_df['h1_mbp_min'].mean())
patient_df['h1_mbp_min'] = patient_df['h1_mbp_min'].apply(lambda h1_mbp_min : mean_h1_mbp_min if pd.isnull(h1_mbp_min) else h1_mbp_min)

mean_h1_mbp_noninvasive_max  = int(patient_df['h1_mbp_noninvasive_max'].mean())
patient_df['h1_mbp_noninvasive_max'] = patient_df['h1_mbp_noninvasive_max'].apply(lambda h1_mbp_noninvasive_max : mean_h1_mbp_noninvasive_max if pd.isnull(h1_mbp_noninvasive_max) else h1_mbp_noninvasive_max)

mean_h1_mbp_noninvasive_min  = int(patient_df['h1_mbp_noninvasive_min'].mean())
patient_df['h1_mbp_noninvasive_min'] = patient_df['h1_mbp_noninvasive_min'].apply(lambda h1_mbp_noninvasive_min : mean_h1_mbp_noninvasive_min if pd.isnull(h1_mbp_noninvasive_min) else h1_mbp_noninvasive_min)

mean_h1_resprate_max  = int(patient_df['h1_resprate_max'].mean())
patient_df['h1_resprate_max'] = patient_df['h1_resprate_max'].apply(lambda h1_resprate_max : mean_h1_resprate_max if pd.isnull(h1_resprate_max) else h1_resprate_max)

mean_h1_resprate_min  = int(patient_df['h1_resprate_min'].mean())
patient_df['h1_resprate_min'] = patient_df['h1_resprate_min'].apply(lambda h1_resprate_min : mean_h1_resprate_min if pd.isnull(h1_resprate_min) else h1_resprate_min)

mean_h1_spo2_max  = int(patient_df['h1_spo2_max'].mean())
patient_df['h1_spo2_max'] = patient_df['h1_spo2_max'].apply(lambda h1_spo2_max : mean_h1_spo2_max if pd.isnull(h1_spo2_max) else h1_spo2_max)

mean_h1_spo2_min  = int(patient_df['h1_spo2_min'].mean())
patient_df['h1_spo2_min'] = patient_df['h1_spo2_min'].apply(lambda h1_spo2_min : mean_h1_spo2_min if pd.isnull(h1_spo2_min) else h1_spo2_min)

mean_h1_sysbp_max  = int(patient_df['h1_sysbp_max'].mean())
patient_df['h1_sysbp_max'] = patient_df['h1_sysbp_max'].apply(lambda h1_sysbp_max : mean_h1_sysbp_max if pd.isnull(h1_sysbp_max) else h1_sysbp_max)

mean_h1_sysbp_min  = int(patient_df['h1_sysbp_min'].mean())
patient_df['h1_sysbp_min'] = patient_df['h1_sysbp_min'].apply(lambda h1_sysbp_min : mean_h1_sysbp_min if pd.isnull(h1_sysbp_min) else h1_sysbp_min)

mean_h1_sysbp_noninvasive_max  = int(patient_df['h1_sysbp_noninvasive_max'].mean())
patient_df['h1_sysbp_noninvasive_max'] = patient_df['h1_sysbp_noninvasive_max'].apply(lambda h1_sysbp_noninvasive_max : mean_h1_sysbp_noninvasive_max if pd.isnull(h1_sysbp_noninvasive_max) else h1_sysbp_noninvasive_max)

mean_h1_sysbp_noninvasive_min = int(patient_df['h1_sysbp_noninvasive_min'].mean())
patient_df['h1_sysbp_noninvasive_min'] = patient_df['h1_sysbp_noninvasive_min'].apply(lambda h1_sysbp_noninvasive_min : mean_h1_sysbp_noninvasive_min if pd.isnull(h1_sysbp_noninvasive_min) else h1_sysbp_noninvasive_min)

In [10]:
print('The shape of our features is:', patient_df.shape)

The shape of our features is: (91713, 96)

In [11]:
patient_df = pd.get_dummies(patient_df)

patient_df.iloc[:,5:].head(5)

,elective_surgery,height,icu_id,pre_icu_los_days,weight,apache_2_diagnosis,apache_3j_diagnosis,apache_post_operative,arf_apache,gcs_eyes_apache,...,icu_admit_source_Other ICU,icu_stay_type_readmit,icu_stay_type_transfer,icu_type_CSICU,icu_type_CTICU,icu_type_Cardiac ICU,icu_type_MICU,icu_type_Med-Surg ICU,icu_type_Neuro ICU,icu_type_SICU
0,0,180.3,92,0.541667,73.9,113.0,502.01,0,0.0,3.0,...,0,0,0,0,1,0,0,0,0,0
1,0,160.0,90,0.927778,70.2,108.0,203.01,0,0.0,1.0,...,0,0,0,0,0,0,0,1,0,0
2,0,172.7,93,0.000694,95.3,122.0,703.03,0,0.0,3.0,...,0,0,0,0,0,0,0,1,0,0
3,1,165.1,92,0.000694,61.7,203.0,1206.03,1,0.0,4.0,...,0,0,0,0,1,0,0,0,0,0
4,0,188.0,91,0.073611,84.0,119.0,601.01,0,0.0,3.0,...,0,0,0,0,0,0,0,1,0,0

In [12]:
X = patient_df[['hospital_death']]

y = patient_df['age']

patient_df_list = list(patient_df.columns)

patient_df = np.array(patient_df)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.30)

In [14]:
print('Training Features Shape:', X_train.shape)
print('Training Labels Shape:', y_train.shape)
print('Testing Features Shape:', X_test.shape)
print('Testing Labels Shape:', y_test.shape)

Training Features Shape: (64199, 1)
Training Labels Shape: (64199,)
Testing Features Shape: (27514, 1)
Testing Labels Shape: (27514,)

In [15]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators = 100)

In [16]:
rf.fit(X_train, y_train)

RandomForestRegressor()

In [17]:
y_pred = rf.predict(X_test)
# Calculate the absolute errors
errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 12.93 degrees.

In [18]:
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 72.54 %.